import { Features } from '@/components/Features/Features';
import { Intro } from '@/components/Intro/Intro';
import { Payments } from '@/components/Payments/Payments';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main-content">
        <Intro />
        <Features />
        <Payments />
      </main>
    </>
  );
}
