import Head from 'next/head';
import { MainContent } from '@/components/MainContent/MainContent';
import { useEffect, useState } from 'react';

export default function Home() {
  const [darkTheme, setDarkTheme] = useState(false);

  useEffect(() => {
    const darkThemeMq = window.matchMedia('(prefers-color-scheme: dark)');
    console.log(darkThemeMq);

    const handleChange = (event) => {
      setDarkTheme(event.matches);
    };

    darkThemeMq.addEventListener('change', handleChange);

    setDarkTheme(darkThemeMq.matches);

    return () => {
      darkThemeMq.removeEventListener('change', handleChange);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-wrapper">
        <main className={`main-content ${darkTheme ? 'dark-theme' : ''}`}>
          <MainContent darkTheme={darkTheme} />
        </main>
      </div>
    </>
  );
}
